### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by NohrR** [RoyalMafia/ryls_airdrops_v2#1]
Console error when I try to put down spawn places for a crate with the tool gun;

[ERROR] addons/ryls_airdrops_v2-master/lua/weapons/gmod_tool/stools/ryl_airdrops_tool.lua:231: attempt to index global 'ryl_airdrop_config' (a nil value)
  1. drawCircle - addons/ryls_airdrops_v2-master/lua/weapons/gmod_tool/stools/ryl_airdrops_tool.lua:231
   2. fn - addons/ryls_airdrops_v2-master/lua/weapons/gmod_tool/stools/ryl_airdrops_tool.lua:110
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by RoyalMafia** [comment]
The only reason why I can think that error is popping up is that you've probably set the config up wrong meaning it's causing an error which is then preventing the script from loading properly. I'd make sure during bootup it isn't throwing any errors etc. I've never seen this error before.

**Comment by RoyalMafia** [comment]
No response. Closing Issue.
